### PR TITLE
make code much more minifier friendly

### PR DESCRIPTION
**Pull request by yellowsink**
cuts our bundle size down by ~0.2kb ish

we now beat simian!!!!!!!!!! (for me sad and epic at same time)

### CODE REVIEW

**Comment by yellowsink** [comment]
update: currently investigating BIG errors while using this in Discord, do not merge yet

**Comment by yellowsink** [comment]
update 2: unreproducible on a second try, if anyone else can repro please say, else i've tried to repro again ~3 times, all unsuccessfully.

**Comment by yellowsink** [comment]
I have no idea what caused this but I suspect it has something to do with the Fucklytics plugin doing weird things to the dispatcher handlers.

If nobody can repro I consider this a false alarm, and all is working as expected

**Comment by twnlink** [comment]
Fucklytics happens to not use the patcher to my knowledge. This can be merged.

**Pull request merged**
